<a href="https://colab.research.google.com/github/JTJxn/Py101/blob/main/Copy_of_Text_Vectorization_AND_Basically_a_Full_Blow_Chatbot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
x1 = pd.DataFrame(["how are you?", "how are you? I", "how are you? I am", "how are you? I am doing", "how are you? I am doing well"])

In [ ]:
y = pd.DataFrame(["I", "am", "doing", "well", "<stop>"])

In [ ]:
my_le.classes_

array(['<stop>', 'I', 'am', 'doing', 'well'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder


my_le = LabelEncoder()


encoded_y = my_le.fit_transform(y)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from tensorflow.keras.layers import Dense, TextVectorization, Embedding, Flatten

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
my_tv = TextVectorization(ragged = True)

In [ ]:
my_tv.adapt(x1)

In [ ]:
my_tv.get_vocabulary()

['',
 '[UNK]',
 np.str_('you'),
 np.str_('how'),
 np.str_('are'),
 np.str_('i'),
 np.str_('am'),
 np.str_('doing'),
 np.str_('well')]

In [ ]:
vocab_size = len(my_tv.get_vocabulary())

In [ ]:
model = Sequential()

In [ ]:
model.add(Embedding(vocab_size, 3))

model.add(Flatten())

model.add(Dense(5, activation = 'softmax'))

model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam')

In [ ]:
transformed_x = my_tv(x1)

In [ ]:
transformed_x = transformed_x.numpy()

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_x = pad_sequences(transformed_x, maxlen = 10)


In [ ]:
padded_x

array([[0, 0, 0, 0, 0, 0, 0, 3, 4, 2],
       [0, 0, 0, 0, 0, 0, 3, 4, 2, 5],
       [0, 0, 0, 0, 0, 3, 4, 2, 5, 6],
       [0, 0, 0, 0, 3, 4, 2, 5, 6, 7],
       [0, 0, 0, 3, 4, 2, 5, 6, 7, 8]], dtype=int32)

In [ ]:
# model.fit(padded_x, encoded_y, epochs = 100)

In [ ]:
input_sentence = "How are you?"

In [ ]:
my_tv(input_sentence)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([3, 4, 2])>

In [ ]:
padded_sentence = pad_sequences([my_tv(input_sentence)], maxlen = 10)

In [ ]:
padded_sentence

array([[0, 0, 0, 0, 0, 0, 0, 3, 4, 2]], dtype=int32)

In [ ]:
stop_token = "<stop>"

while True:

  output_probs = model.predict(padded_sentence, verbose = 0)

  # print(output_probs)

  output_index = output_probs.argmax()

  # print(output_index)

  output_text_set = my_le.inverse_transform([output_index])

  # print(output_text_set)

  true_output_text_token = output_text_set[0]

  # print(true_output_text_token)

  if true_output_text_token == stop_token:

    # print("stop token detected!")
    break #stop generating

  else:
    print(true_output_text_token, end = " ")

  internal_sentence_array = padded_sentence[0] #array of arrays -> 2D

  internal_sentence_list = internal_sentence_array.tolist() #convert to a list so that I can append it

  my_encoded_token = my_tv(true_output_text_token) #can't append the text, I need a number, so I need to convert the text to the proper number

  my_integer = my_encoded_token.numpy().tolist()[0]

  internal_sentence_list.append(my_integer)

  padded_sentence = pad_sequences([internal_sentence_list], maxlen = 10)

I am doing well 